### ISSUE TITLE
Generate styles.css for reference purposes

### ISSUE THREAD

**Issue by petervangennip** [websitejs/websitejs#30]
Instead of only generating a styles.min.css, lets also generate a styles.css so the generated classes can be checked

**Comment by roccojanse** [comment]
Hi Peter, do we actually need checking of generated classes? The current version is leaving out the styles.css on purpose, because i think we shouldn't need to check generated styles. And if we need to check these classes i think we should use a browsers inspector (like chrome or firebug). What do you think?

**Comment by petervangennip** [comment]
Personally I would like to have this. There are scenario's where you want to check all the generated css in a readable file. It's only one file extra but I do agree it's only one file that is not used often. Maybe @mijnnaamisramon @Sharonvdg  and @peterbust can give their opinion about this.

**Comment by websitejs** [comment]
I still think this is a bit of a overhead, with .map files and the console our code should be pretty debuggable and this therefore shouldn't be necessary. But, as @pwavg stated, what do you guys (and gal) think @mijnnaamisramon , @Sharonvdg and @peterbust?

**Comment by peterbust** [comment]
Personally I don't  find it useful in this particular setup. I'd like to explore the scenario where we serve files from **./src** though. I like the scenario where **./dist** holds an **index.html** in the root and works without a local server (including concatenated and minified JS and CSS) . And  where **./src** holds individual (maximized) CSS and JS files. Makes more sense to me. But unrelated for this issue.
